// Code generated by dingo; DO NOT EDIT
package main

type Container struct {
	CustomerWelcome	*CustomerWelcome
	SendEmail	EmailSender
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{}
}
func (container *Container) GetCustomerWelcome() *CustomerWelcome {
	if container.CustomerWelcome == nil {
		service := &CustomerWelcome{}
		service.Emailer = container.GetSendEmail()
		container.CustomerWelcome = service
	}
	return container.CustomerWelcome
}
func (container *Container) GetSendEmail() EmailSender {
	if container.SendEmail == nil {
		service := &SendEmail{}
		service.From = "ranchocooper@gmail.com"
		container.SendEmail = service
	}
	return container.SendEmail
}
